on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    
    steps:
    - name: ssh install
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          rm -rf ${{ secrets.WORK_DIR }} &&
          git clone ${{ secrets.REPO_URL }} ${{ secrets.WORK_DIR }} &&
          cd ${{ secrets.WORK_DIR }} &&
          echo "${{ secrets.DOTENV}}" > .env &&

          #python
          python3 -m venv ./ &&
          source ./bin/activate &&
          pip install -r requirements.txt
