on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    
    steps:
    - name: ssh install
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo systemctl stop obibot.service &&
          cd ${{ secrets.WORK_DIR }} &&
          git pull &&
          echo "${{ secrets.DOTENV}}" > .env &&
          sudo systemctl start obibot.service
